import type { ProjectFileInput } from "../../services/projects";
import {
  DEFAULT_PROJECT_POLICY,
  getPinnedPackageVersions,
  type ProjectPolicy,
} from "./projectPolicy";
import { isRecord } from "./records";

export function validateGeneratedPackageJson(
  files: ProjectFileInput[],
  policy: ProjectPolicy = DEFAULT_PROJECT_POLICY,
) {
  const packageFile = files.find((file) => file.path === "package.json");

  if (!packageFile) {
    throw new Error("Invalid model response: generated project is missing package.json.");
  }

  validatePackageJsonContent(packageFile.content, policy);
}

export function validatePackageJsonContent(
  content: string,
  policy: ProjectPolicy = DEFAULT_PROJECT_POLICY,
) {
  let parsed: unknown;

  try {
    parsed = JSON.parse(content);
  } catch (error) {
    throw new Error(`Invalid package.json generated by model: ${String(error)}`);
  }

  if (!isRecord(parsed)) {
    throw new Error("Invalid package.json generated by model: root must be an object.");
  }

  const scripts = isRecord(parsed.scripts) ? parsed.scripts : {};
  const dependencies = isRecord(parsed.dependencies) ? parsed.dependencies : {};
  const devDependencies = isRecord(parsed.devDependencies)
    ? parsed.devDependencies
    : {};
  const allDependencies = {
    ...dependencies,
    ...devDependencies,
  };

  for (const [dependency, version] of Object.entries(allDependencies)) {
    if (typeof version !== "string" || !isPinnedSemver(version)) {
      throw new Error(
        `Invalid package.json generated by model: ${dependency} must use an exact pinned semver version, got "${String(version)}".`,
      );
    }
  }

  for (const [dependency, expectedVersion] of Object.entries(
    getPinnedPackageVersions(policy),
  )) {
    const actualVersion = allDependencies[dependency];

    if (typeof actualVersion !== "string") {
      throw new Error(
        `Invalid package.json generated by model: missing ${dependency}.`,
      );
    }

    if (actualVersion !== expectedVersion) {
      throw new Error(
        `Invalid package.json generated by model: ${dependency} must be pinned to "${expectedVersion}", got "${actualVersion}".`,
      );
    }
  }

  for (const [name, expectedCommand] of Object.entries(
    policy.packageJson.requiredScripts,
  )) {
    if (typeof scripts[name] !== "string" || !scripts[name].includes(expectedCommand)) {
      throw new Error(
        `Invalid package.json generated by model: scripts.${name} must include "${expectedCommand}".`,
      );
    }
  }
}

function isPinnedSemver(version: string) {
  return /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(version);
}
