import type { ProjectFileInput } from "../../services/projects";
import { isRecord } from "./records";

const PINNED_PACKAGE_VERSIONS = new Map([
  ["next", "14.2.35"],
  ["react", "18.3.1"],
  ["react-dom", "18.3.1"],
  ["typescript", "5.4.5"],
  ["tailwindcss", "3.4.17"],
  ["postcss", "8.4.49"],
  ["autoprefixer", "10.4.20"],
  ["@types/node", "20.14.11"],
  ["@types/react", "18.3.3"],
  ["@types/react-dom", "18.3.0"],
]);

export function validateGeneratedPackageJson(files: ProjectFileInput[]) {
  const packageFile = files.find((file) => file.path === "package.json");

  if (!packageFile) {
    throw new Error("Invalid model response: generated project is missing package.json.");
  }

  validatePackageJsonContent(packageFile.content);
}

export function validatePackageJsonContent(content: string) {
  let parsed: unknown;

  try {
    parsed = JSON.parse(content);
  } catch (error) {
    throw new Error(`Invalid package.json generated by model: ${String(error)}`);
  }

  if (!isRecord(parsed)) {
    throw new Error("Invalid package.json generated by model: root must be an object.");
  }

  const scripts = isRecord(parsed.scripts) ? parsed.scripts : {};
  const dependencies = isRecord(parsed.dependencies) ? parsed.dependencies : {};
  const devDependencies = isRecord(parsed.devDependencies)
    ? parsed.devDependencies
    : {};
  const allDependencies = {
    ...dependencies,
    ...devDependencies,
  };

  for (const [dependency, version] of Object.entries(allDependencies)) {
    if (typeof version !== "string" || !isPinnedSemver(version)) {
      throw new Error(
        `Invalid package.json generated by model: ${dependency} must use an exact pinned semver version, got "${String(version)}".`,
      );
    }
  }

  for (const [dependency, expectedVersion] of PINNED_PACKAGE_VERSIONS) {
    const actualVersion = allDependencies[dependency];

    if (typeof actualVersion !== "string") {
      throw new Error(
        `Invalid package.json generated by model: missing ${dependency}.`,
      );
    }

    if (actualVersion !== expectedVersion) {
      throw new Error(
        `Invalid package.json generated by model: ${dependency} must be pinned to "${expectedVersion}", got "${actualVersion}".`,
      );
    }
  }

  const requiredScripts = new Map([
    ["dev", "next dev"],
    ["build", "next build"],
    ["start", "next start"],
  ]);

  for (const [name, expectedCommand] of requiredScripts) {
    if (typeof scripts[name] !== "string" || !scripts[name].includes(expectedCommand)) {
      throw new Error(
        `Invalid package.json generated by model: scripts.${name} must include "${expectedCommand}".`,
      );
    }
  }
}

function isPinnedSemver(version: string) {
  return /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(version);
}
